apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/karimdeif/multi-tenancy"
    - name: revision
      value: "master"
